#!/usr/bin/env python3
"""Generate a controlled live-paper round-trip scenario.

The limit price has to be set against the LIVE market price at run time, which
a static fixture cannot hardcode -- so this writes the scenario JSON from a
price you look up seconds before the run. No hand-editing.

TWO MODES

  resting     BUY limit priced well BELOW market (default -18%). A buy bid far
              under the market cannot execute, so the order rests as `open` at
              the broker until it is cancelled. Zero fill risk.
              Exercises: submit -> open -> cancel -> persisted.

  marketable  BUY limit priced slightly ABOVE market (default +0.5%), smallest
              sensible size. A buy limit at or above the offer executes
              immediately.
              Exercises: submit -> fill -> poll_order_updates records the fill
              with the broker's real trade_id as broker_fill_id -> position
              updated -> cash reconciled.

WHY A "WRONG" PRICE STILL PASSES RISK

Risk rule 7 (`limit_price_max_deviation_pct`, default 3%) compares the limit
against the last price core has been TOLD -- which comes from the market-data
batch (agent.py feeds `batch.last_prices` into the risk context), not from the
broker. With `--md-source mock` that price is whatever this file scripts. So
the scripted quote is written AT the limit price (deviation 0.00%), while the
real market sits ~18% higher. Risk is satisfied by a self-consistent picture;
the broker prices against reality and the order rests. That divergence is the
entire trick of the resting test, and it only works because md is mocked --
which preserves the intended isolation (broker real,
everything else scripted).

This script places no orders and needs no credentials -- it only writes a file.

Usage:
    # Look the price up first with the quote smoke tool, if it was built:
    ../build/md/tevnnis-md-longbridge-smoke NVDA.US

    uv run python scripts/make_paper_roundtrip.py \
        --mode resting --symbol NVDA.US --price 182.45
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

DEFAULT_CONFIG = Path(__file__).resolve().parents[2] / "config" / "config.paper.yaml"


def sector_for(universe: dict[str, list[str]], symbol: str) -> str:
    for sector, symbols in universe.items():
        if symbol in symbols:
            return sector
    raise SystemExit(
        f"{symbol} is not in the config universe (the allowlist IS the filter, §6). "
        f"Choose one of: {', '.join(sorted(s for v in universe.values() for s in v))}"
    )


def build(args: argparse.Namespace) -> tuple[dict, list[str]]:
    config = yaml.safe_load(Path(args.config).read_text())
    universe = config["universe"]
    limits = config["risk_limits"]
    managed_capital = float(config["account"]["managed_capital"])

    sector = sector_for(universe, args.symbol)

    if args.mode == "resting":
        limit_price = round(args.price * (1.0 - args.discount_pct / 100.0), 2)
    else:
        limit_price = round(args.price * (1.0 + args.premium_pct / 100.0), 2)

    notional = limit_price * args.quantity

    # Pre-flight the Risk Engine's caps here, so a rejection shows up now
    # rather than after a live order round-trip has been set up.
    problems: list[str] = []
    position_cap = limits["max_position_pct"] * managed_capital
    sector_cap = limits["max_sector_pct"] * managed_capital
    reserve = limits["min_cash_reserve_pct"] * managed_capital
    if notional > limits["max_order_notional"]:
        problems.append(
            f"notional {notional:,.2f} exceeds max_order_notional "
            f"{limits['max_order_notional']:,.2f}"
        )
    if notional > position_cap:
        problems.append(
            f"notional {notional:,.2f} exceeds the per-symbol cap {position_cap:,.2f} "
            f"(max_position_pct {limits['max_position_pct']} x managed_capital "
            f"{managed_capital:,.0f}) — reduce --quantity"
        )
    if notional > sector_cap:
        problems.append(f"notional {notional:,.2f} exceeds the sector cap {sector_cap:,.2f}")
    if args.cash - notional < reserve:
        problems.append(
            f"cash after the order ({args.cash - notional:,.2f}) would fall below the "
            f"required reserve {reserve:,.2f} (min_cash_reserve_pct)"
        )

    event_id = f"paper-roundtrip-{args.mode}-{args.symbol}"
    # change_pct is what made this a HIGH event; it must clear the config's
    # escalation bands to be plausible, but nothing keys off the exact value.
    change_pct = 4.2

    scenario = {
        "_comment": (
            "GENERATED by scripts/make_paper_roundtrip.py for a controlled paper "
            "live-paper round-trip. Do not commit or hand-edit: the limit price is "
            "only valid against the market price it was generated from. Regenerate "
            "before every run. The `broker` section is deliberately absent — with "
            "--broker longbridge the real adapter replaces the mock entirely."
        ),
        "_generated_from": {
            # Stamped so a stale file is obvious: a limit price is only valid
            # against the market it was generated from. Regenerate before every
            # run and check the LIMIT PRICE line the script prints.
            "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "mode": args.mode,
            "symbol": args.symbol,
            "observed_market_price": args.price,
            "limit_price": limit_price,
            "offset_pct": round((limit_price / args.price - 1.0) * 100.0, 2),
        },
        "market_data": [
            {
                "events": [
                    {
                        "event_id": event_id,
                        "type": "QUOTE_MOVE",
                        "symbol": args.symbol,
                        "sector": sector,
                        # HIGH clears cadence.reason_min_priority, so the cheap
                        # gate wakes the (mock) LLM instead of logging a HOLD.
                        "priority": "HIGH",
                        "quote": {
                            # Scripted AT the limit price: risk rule 7 measures
                            # deviation against THIS, not the real market.
                            "last_price": limit_price,
                            "prev_close": round(limit_price / (1 + change_pct / 100), 2),
                            "change_pct": change_pct,
                            "intraday_high": limit_price,
                            "intraday_low": round(limit_price * 0.99, 2),
                            "volume": 1_000_000,
                            "trigger": "cross_+3pct",
                        },
                    }
                ],
                "snapshots": {sector: [[args.symbol, limit_price, change_pct]]},
                "next_cursor": "paper-roundtrip-1",
            }
        ],
        "llm": [
            {
                "session_note": f"Controlled {args.mode} round-trip — scripted, not a real view.",
                "instructions": [
                    {
                        "action": "BUY",
                        "symbol": args.symbol,
                        "quantity": args.quantity,
                        "limit_price": limit_price,
                        # 0 => no TIF deadline, so expire_timed_orders never
                        # auto-cancels it. The resting order stays working until
                        # shutdown cancels it (cancel_open_orders_on_shutdown),
                        # which is the path under test.
                        "valid_seconds": 0,
                        "confidence": 0.75,
                        "thesis": f"Controlled paper {args.mode} round-trip.",
                        "cited_event_ids": [event_id],
                    }
                ],
            }
        ],
    }
    return scenario, problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a controlled live-paper round-trip scenario.",
    )
    parser.add_argument("--mode", choices=["resting", "marketable"], required=True)
    parser.add_argument("--symbol", default="NVDA.US", help="must be in the config universe")
    parser.add_argument(
        "--price", type=float, required=True, help="the LIVE market price you just looked up"
    )
    parser.add_argument("--quantity", type=int, default=1)
    parser.add_argument(
        "--discount-pct", type=float, default=18.0, help="resting mode: %% below market"
    )
    parser.add_argument(
        "--premium-pct", type=float, default=0.5, help="marketable mode: %% above market"
    )
    parser.add_argument("--cash", type=float, default=3000.0, help="USD cash, for the pre-flight")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--out", help="default: scenario.paper_<mode>.json next to --config")
    args = parser.parse_args(argv)

    if args.price <= 0:
        raise SystemExit("--price must be positive")

    scenario, problems = build(args)
    default_out = Path(args.config).parent / f"scenario.paper_{args.mode}.json"
    out = Path(args.out) if args.out else default_out
    out.write_text(json.dumps(scenario, indent=2) + "\n")

    meta = scenario["_generated_from"]
    print(f"wrote {out}")
    print(f"  generated at   : {meta['generated_at_utc']}  (regenerate if this is not now)")
    print(f"  mode           : {args.mode}")
    print(f"  symbol         : {args.symbol}")
    print(f"  market price   : {meta['observed_market_price']:.2f}  (as you observed it)")
    print(f"  LIMIT PRICE    : {meta['limit_price']:.2f}  ({meta['offset_pct']:+.2f}% vs market)")
    print(f"  quantity       : {args.quantity}")
    print(f"  notional       : {meta['limit_price'] * args.quantity:,.2f} USD")
    print(f"  scripted quote : {meta['limit_price']:.2f}  (0.00% deviation -> passes risk rule 7)")
    if args.mode == "resting":
        print("  expectation    : rests as OPEN at the broker; cannot fill; cancelled at shutdown")
    else:
        print("  expectation    : marketable — fills immediately at or near the market")

    if problems:
        print("\nRISK PRE-FLIGHT WOULD REJECT THIS ORDER:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1
    print("\nrisk pre-flight: OK (order notional, position/sector caps, cash reserve)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
